### ISSUE TITLE
test for base64 and base66

### ISSUE THREAD

**Issue by Kikobeats** [cryptocoinjs/base-x#12]
I feel that this implementation is different to base64 standard implementation. What happens?

**Comment by dcousens** [comment]
> bitcoin style leading zero compression

And please read [this](https://github.com/cryptocoinjs/base-x#how-it-works).

**Comment by dcousens** [comment]
Maybe it is worth putting a bigger warning on the repository to those who might be confused?

**Comment by Kikobeats** [comment]
yes xD
