### ISSUE TITLE
Base64 padding

### ISSUE THREAD

**Issue by axic** [cryptocoinjs/base-x#17]
Is there a way to make base64 decoding work with padded input (`=` signs at the end) without significant changes?

**Comment by dcousens** [comment]
ping @sublimator

**Comment by fanatid** [comment]
I think answer is *no*, because base64 has length that depends only from input length (bitcoin base58 length also depends from values in input).

**Comment by fanatid** [comment]
Also I want add that `base-x` based on division while `base64` convert 3x bytes for 4x.
