### ISSUE TITLE
Weird issue with zero padding using base-36

### ISSUE THREAD

**Issue by axic** [cryptocoinjs/base-x#18]
The output should be 30 characters for anything below `0x088f924eeceeda7fe92e1f5b0fffffffffffffff`.

`0x01c5496aee77c1ba1f0854206a26dda82a81d6d8` is the following 30 characters: `7G1Y2YAHPUXSL8TQCWG49R290QSOUW`.

Strangely `0x00c5496aee77c1ba1f0854206a26dda82a81d6d8` gets a 0 prefix making it 31 characters (which can be omitted and it decodes properly): `038O073KYGTWWZN0F2WZ0R8PX5ZPPZS`

Any reason for base-x behaving this way?  What is described in the README can be the cause, but it doesn't seem to be consistent, given a larger input number results in a smaller base-36 number.

Test code:
```js
var BASE36_ALPHABET = '0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ'
var bs36 = require('base-x')(BASE36_ALPHABET)
var hex = require('convert-hex')

console.log(bs36.encode(hex.hexToBytes('00c5496aee77c1ba1f0854206a26dda82a81d6d8'))) // 038O073KYGTWWZN0F2WZ0R8PX5ZPPZS
console.log(bs36.encode(hex.hexToBytes('01c5496aee77c1ba1f0854206a26dda82a81d6d8'))) // 7G1Y2YAHPUXSL8TQCWG49R290QSOUW
```

**Comment by dcousens** [comment]
@sublimator is probably the best guy for this

**Comment by fanatid** [comment]
@axic leading '0' here for encoding first zero byte, in bitcoin base58 it will be '1'

check next snippet (if you remove leading '0' you lose first byte!):
```js
var BASE36_ALPHABET = '0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ'
var bs36 = require('base-x')(BASE36_ALPHABET)

console.log(bs36.encode(new Buffer('00c5496aee77c1ba1f0854206a26dda82a81d6d8', 'hex'))) // 038O073KYGTWWZN0F2WZ0R8PX5ZPPZS
console.log(bs36.encode(new Buffer('01c5496aee77c1ba1f0854206a26dda82a81d6d8', 'hex'))) // 7G1Y2YAHPUXSL8TQCWG49R290QSOUW
console.log(new Buffer(bs36.decode('038O073KYGTWWZN0F2WZ0R8PX5ZPPZS')).toString('hex')) // 00c5496aee77c1ba1f0854206a26dda82a81d6d8
console.log(new Buffer(bs36.decode('38O073KYGTWWZN0F2WZ0R8PX5ZPPZS')).toString('hex')) // c5496aee77c1ba1f0854206a26dda82a81d6d8
```

https://github.com/cryptocoinjs/base-x/blob/fd05cce3a060b617d61991b521783a98c9524c09/index.js#L38
https://github.com/cryptocoinjs/base-x/blob/fd05cce3a060b617d61991b521783a98c9524c09/index.js#L73

**Comment by axic** [comment]
Yes, the first byte is missing on decoding, but parsing that as a number will result in the same value, with our without 00 prefix.

And as mentioned, a bigger number (ie. starting with 01) will result in a shorter (the correct) output.

In short I think `00c5496aee77c1ba1f0854206a26dda82a81d6d8` should be encoded as `38O073KYGTWWZN0F2WZ0R8PX5ZPPZS` and decoded as `00c5496aee77c1ba1f0854206a26dda82a81d6d8`.

**Comment by fanatid** [comment]
`00c5496aee77c1ba1f0854206a26dda82a81d6d8` -> `38O073KYGTWWZN0F2WZ0R8PX5ZPPZS` -> `00c5496aee77c1ba1f0854206a26dda82a81d6d8`
it's impossible, because you can't say how many zero bytes you should put in head on decoding...

**Comment by fanatid** [comment]
[wiki](https://en.wikipedia.org/wiki/Base58) says that base58 is good for encoding large numbers, not binary data, TBH I don't fully understand why.
Probably `base-x` was not is the best name for this package.

**Comment by dcousens** [comment]
@fanatid mmm
