### ISSUE TITLE
Possible performance increase

### ISSUE THREAD

**Issue by dcousens** [cryptocoinjs/base-x#19]
@fanatid note https://github.com/uphold/bitcoin/blob/enhancement/speedup-encodebase58/src/base58.cpp#L80-L88 (from https://github.com/bitcoin/bitcoin/pull/7656)  it seems possible we could take advantage of this too.

**Comment by jprichardson** [comment]
@dcousens 

1. Are you suggesting using C++ here?
2. Is it accurate that this code comes from Uphold Inc? The same one that is being accused of being founded by the patent troll? Do you think that could pose additional risks?

**Comment by dcousens** [comment]
> Are you suggesting using C++ here?

Nope,  just adapting the same algorithmic change.

> Is it accurate that this code comes from Uphold Inc? The same one that is being accused of being founded by the patent troll? Do you think that could pose additional risks?

I'm not aware of the case,  but this is being submitted by @promag to the bitcoin/bitcoin repository,  which is MIT.  So,  provided we give credit to that repository and @promag,  I think we should fine (as we are also [MIT](https://github.com/cryptocoinjs/base-x/blob/master/LICENSE.md))

**Comment by fanatid** [comment]
@dcousens it will not work here, we don't preallocate digits

**Comment by fanatid** [comment]
If we decide preallocate digits we can removing reverse at the end, but we still need loop for converting digits to alphabet. I think PR from bitcoin doesn't make sense for us.

**Comment by dcousens** [comment]
@fanatid I think pre-allocating the digits might be worthwhile investigating.

**Comment by fanatid** [comment]
Probably yes, since it's used primarily in `bs58` for bitcoin addresses we can preallocate global array and use it in some cases.

**Comment by fanatid** [comment]
Array preallocation not gives significant performance and makes code more complex.
not complete branch (but run benchmark with new feature is possible): [feature/preallocated-array](https://github.com/cryptocoinjs/base-x/tree/feature/preallocated-array)
