### ISSUE TITLE
Buffer as decode return value

### ISSUE THREAD

**Issue by dcousens** [cryptocoinjs/base-x#27]
I just had several hours burned because I forgot this is *not* the case.

Whyyyyyyyyyy.

Can we just return a `Buffer`?

Yes, it would be a breaking change.

**Comment by dcousens** [comment]
ping @jprichardson was there any reason?

**Comment by jprichardson** [comment]
> ping @jprichardson was there any reason?

I believe it was to retain maximum compatibility across platforms.

> Can we just return a Buffer?

On a personal level, IDC if we change. The question is... 'should' we return a Buffer? I don't know.

**Comment by dcousens** [comment]
> The question is... 'should' we return a Buffer? I don't know.

IMHO, yes.
`Buffer` is very compatible across platforms using modern work flows.

I think the risk of this being passed interchange-ably to hash functions and other encoding functions which *expect* a `Buffer`, is much higher priority.

**Comment by dcousens** [comment]
Closing in favour of https://github.com/cryptocoinjs/base-x/pull/28
