### ISSUE TITLE
base-x is not compatible with AWS Lambda Execution Environment (Node LTS 4.3.2)

### ISSUE THREAD

**Issue by n8sabes** [cryptocoinjs/base-x#35]
Package engine requirement makes base-x incompatible with AWS Lambda deployments. Lambda's current execution environment is Node LTS 4.3.2 and is not expected to move to LTS 6 until April 2017.

[package.json : line 41](https://github.com/cryptocoinjs/base-x/blob/v2.0.4/package.json#L41)

```
  "engines": {
    "node": ">=4.5.0"
  }
```

Is there any reason this cannot be revised back to 4.3.2?

**Comment by sublimator** [comment]
We should add 4.3.2. to the .travis.yml build matrix.

**Comment by sublimator** [comment]
I have been out of the node.js loop 6 months but currently working on a
lambda project. I hear node 8 is to be released in a few months. AWS still
on 4.3.x ??? Is that an LTS or something?

**Comment by sublimator** [comment]
On the other hand libs steaming ahead and keeping pace with node engines
ought to pressure AWS to "do the right thing" huh ? Lol

**Comment by sublimator** [comment]
http://whatdoeslambdasupport.com

sigh

**Comment by fanatid** [comment]
This come from https://github.com/cryptocoinjs/base-x/pull/32
Unfortunately only after release we found, that `Buffer.from` not works in all `4.x` versions, so `2.0.4` was released with `engines.node >= 4.5.0`.
You can still use this project at AWS if install and hold specific versions: `~2.0.0`
Sorry about this :(

**Comment by n8sabes** [comment]
I completely agree that Amazon should be faster to support LTS builds, and they should also enable "experimental" support of non-LTS execution environments. Below are links to the respective service's and versions as of today:

[AWS Lambda](http://docs.aws.amazon.com/lambda/latest/dg/current-supported-versions.html) @ v4.3.2
[Google Cloud Functions](https://cloud.google.com/nodejs/resources/runtime) @ v4.1.2 default, but changeable
[Azure Cloud Functions](https://docs.microsoft.com/en-us/azure/azure-functions/functions-reference-node#node-version--package-management) @ v6.5.0
[IBM OpenWhisk](https://www.ibm.com/blogs/bluemix/2016/12/node-js-code-openwhisk-actions/) @ v0.12.17 and v6.9.1

Node LTS release schedule is [here](https://github.com/nodejs/LTS).

I'll use your workaround and rollback to 2.0.0 for now and check the improvements/fixes from 2.0.0 to 2.0.4 to determine if they're relevant.

Thanks for the great work on base-x and sharing it -- very much appreciated.

😄

**Comment by dcousens** [comment]
@fanatid potentially we could rollback,  then release as `3.0.0`.
`2.0.4` will always be broken,  but not `^2.0.0`

**Comment by n8sabes** [comment]
If no functionality or improvements are lost, base-x is more robust and more broadly compatible, by all means, that sounds like a great plan.

**Comment by fanatid** [comment]
@dcousens I agree

**Comment by dcousens** [comment]
Deprecated `2.0.1->2.0.4`.
Published `2.0.5` without safe buffer changes or engine restrictions
Published `3.0.0` with safe buffer changes and `4.5.0` engine restriction.

@fanatid I rebased/squashed and force pushed from 35cae44359f9df36ee4fe5c9e3ae156d023467d3,  to avoid confusion and keep the extra fixes that were added since.

See https://github.com/cryptocoinjs/base-x/commits/master for the 5 commits to review (if needed).

**Comment by n8sabes** [comment]
Everything is working great now -- **Thanks for the fix!** 👍 

Two points:

1) Not seeing the tag in the Branch drop down tags tab, but NPM / Yarn installs fine using @2.0.5.
2) It might save people time if you added the following statement to your `Readme.md`:

Legacy Node execution environments below 4.5.0 should use base-x version 2.0.5.

**Comment by dcousens** [comment]
@n8sabes up to make the README change PR?

**Comment by n8sabes** [comment]
Refreshed browser a few times, but still isn't showing up for me. Weird. Maybe there is some system latency / catching going on, or I'm not looking in the right spot. No worries.

![2017-02-13_14-21-14](https://cloud.githubusercontent.com/assets/10445528/22906077/caf0395c-f1f7-11e6-95fa-c48116252b54.jpg)

**Comment by dcousens** [comment]
@n8sabes indeed,  actually `2.0.5` wasn't there.
Fixed.
