### ISSUE TITLE
Revert to ES5

### ISSUE THREAD

**Issue by tphanson** [cryptocoinjs/base-x#51]
Hi base-x team! It is a simple error so I wont make it lengthy. I met some kind of this error ```Failed to minify the code from this file``` and it was base-x changed to use es6, to fix this error, could the team support babel or at least, just code it in es5 style?
Thanks team so much.

**Comment by dcousens** [comment]
I am ok to do this,  but,  is there any reason people don't transpile their node_modules too?

**Comment by dcousens** [comment]
Are you using babel?

**Comment by dcousens** [comment]
Are you using babel?

**Comment by tphanson** [comment]
Yes I am. And I believe most of modules in npm are using babel to formalize their code before publish.

**Comment by dcousens** [comment]
Then why not use babel on your `node_modules`?

**Comment by tphanson** [comment]
Ah sorry, I misunderstood you. The reason I don't use babel, in fact, I cannot, because I am using React and it's restricted to modify the default config of react (babel, webpack, uglify...) so when react run, it may always require node_modules in normalized form (es5). So yeah, this was the case I am stuck.

**Comment by tphanson** [comment]
Here the picture of error in case you need to clarify what i am talking about.

**Comment by blackwatertepes** [comment]
I'm getting the same error that @tphanson  is experiencing. It's fine to use es6+ JS in your `src`, as long as you transpile down to es5 into a `dist` before publishing. Best practice is to use a `prepublish` command, in your package.json `scripts` that builds the project, and transpiles your javascript. Also, remember to add `dist` do your .gitignore, ;)

**Comment by dcousens** [comment]
I'm happy to move it back to ES5 to avoid the endless discussion,  but,  it is as trivial for you to simply add modules to your build step.

Compiling a `dist` is **not**  best practice except if you give zero care about your application security.

**Comment by traylewin** [comment]
If you really want to satisfy everyone here, you could tag this version as 3.1.0 so that existing dependent projects won't try to upgrade from the 3.0.4 version. You'd also need to publish a 3.0.6 version that reverts back to the same code that you had in 3.0.4 (or unpublish 3.0.5). We'd really appreciate it if you could do this - there is a hackathon this weekend and this fix would make a big difference for the teams.

**Comment by dcousens** [comment]
I'll patch to ES5

**Comment by dcousens** [comment]
Remembering you can use GitHub site tly for dependencies if the patch doesn't merge in time...

**Comment by tphanson** [comment]
So, i can close it. Thanks you for your contribution.

**Comment by maksympc** [comment]
Hello, have you any updates with this issue?

**Comment by mtsalenc** [comment]
Was this ever fixed? It seems any project depending on bs58 or eosjs-cc won't build!

**Comment by singhpratyush** [comment]
Hi,

Will this be fixed anytime soon?

For other looking for a solution, take a look at https://github.com/FeeSimple/data-manager/pull/44. This would do the job for you.

**Comment by sgehrman** [comment]
needs a solution

**Comment by junderw** [comment]
I am the new maintainer.

I am slowly moving everything to TypeScript, so these types of issues shouldn't be too bad anymore... but a quick question.

## Are we really going to use ES5 for the rest of all eternity?

Yes, TypeScript, Webpack, Babel, etc etc etc... all transpile things and allow them to run smoothly on oooooooold environments that only support ES5...

But there are some features in later ES revisions that can not be transpiled or polyfilled into ES5...

I wonder when we can shake the monkey off our back that is ES5...

Talk to React? Talk to Webpack? Talk to Babel? Talk to Electron?

Everyone is so afraid of backwards compat that everyone targets ES5 and we all stay stuck in the stone ages...

## Rant over

I'll rewrite this for TypeScript, target ES5 and publish.
