### ISSUE TITLE
android run time error, "undefined is not a function (evaluating 'BASE_MAP.fill(255)')"

### ISSUE THREAD

**Issue by lxlhum** [cryptocoinjs/base-x#56]
![error](http://img.mukewang.com/szimg/5c600d770001ad9f10021632.jpg)
my friend use base58 function in her react-native app. But the lastVersion base-x take an error for her app. The error is "undefined is not a function (evaluating 'BASE_MAP.fill(255)')"

I downgrade base-x to @3.0.4, everything is ok....I think this is a bug, so I issue it.

**Comment by talhajunaidd** [comment]
#54 Fixes the issue however it is still waiting for the review.

**Comment by talhajunaidd** [comment]
We fixed the issue by importing combined polyfill for [Array.prototype.fill()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/fill#Polyfill) and [TypedArray.prototype.fill()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypedArray/fill#Polyfill).  
The polyfill we used is given [here](https://gist.github.com/talhajunaidd/81b5b7416964ea795dbbb29f046476b4)

Thanks, @ahmedkhan1039 for the idea of combining the polyfill.

**Comment by johnjayasingh** [comment]
Can we publish the change?

**Comment by ahmedkhan1039** [comment]
@johnjayasingh  What change ?

**Comment by johnjayasingh** [comment]
The last publish for base-x project was made 5 months ago in npm js. I was getting this error last week also. then i had to make temporary fixes in nodemodules

**Comment by ahmedkhan1039** [comment]
You can import [this](https://gist.github.com/talhajunaidd/81b5b7416964ea795dbbb29f046476b4) polyfill at the start of your project and you will not need to change anything in node modules
