### ISSUE TITLE
Base32 alphabet

### ISSUE THREAD

**Issue by roccomuso** [cryptocoinjs/base-x#66]
On README the indicated base32 alphabet is `0123456789ABCDEFGHJKMNPQRSTVWXYZ`
But it should be `ABCDEFGHIJKLMNOPQRSTUVWXYZ234567`.

PS. Oh I also read that uses a different encoding. So it will always return a wrong value compared to other encoders.

**Comment by junderw** [comment]
We are not RFC 4648 compliant, so using that alphabet might mislead users into thinking we are.

Thanks for the issue!
