### ISSUE TITLE
Why do encoded results have inconsistent length when input length is constant

### ISSUE THREAD

**Issue by jfriend00** [cryptocoinjs/base-x#67]
I'm using a base58 encoding and I noticed that the encoded strings are not always the same length.   
I have a desire for all encoded values to be the same length.   Why is this?  Is it necessary?

Here's a code example that results in a 21 character result instead of a 22 character result:

```
// create base58 encoder that uses only alpha numerics and leaves out O and 0 which get confused
const base58Encode = require('base-x')('123456789ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz').encode;

const testData = Buffer.from([0x02, 0x3d, 0xab, 0x4f, 0x48, 0xcb, 0x79, 0xf9, 0x1c, 0x7e, 0x21, 0x97, 0xe7, 0xb1, 0xa0, 0x55]);

let str = base58Encode(testData);
console.log(str);
```

**Comment by jfriend00** [comment]
After a little more reading on the topic, I've come to find that this is just the way it is.  Sometimes the result fits in a lesser number of characters.  It is reversible with encode()/decode() so there's no missing data.  I guess I'll just pad to the longest length if I want a consistent length.

**Comment by junderw** [comment]
The best way to think of it:

> this library only manages padding on a byte level. So 0x00 0x01 0xff will have one character of padding, however, 0x01 0xff doesn't store any padding information even though there are 7 bits of 0s at the top. But it doesn't matter, since the only way to show 0x1ff in bytes is by having 2 bytes... since this library just basically takes the integer of 0x1ff and converts it into a string, depending on the base and data, 0xffff and 0x1ff could have more base characters even if they have the same byte length.

This is one of the reasons why we make it clear that this library when used with the BASE64 alphabet will NOT produce valid base64 strings (in the sense of your average base64 library) since we use a different method. (Normal base64 libraries split bytes up into 6 bit chunks and encode. We don't)
